import { AppMessages } from './LocalizationTypes';

const english: AppMessages = {
  corporativeDirectory: {
    retrievingData: 'Retrieving employee data',
    showSkills: '{0}\'s skills',
    closeDialog: 'Close',
    headers: {
      avatar: 'Avatar',
      name: 'Name',
      position: 'Position',
      skills: 'Skills',
    },
  },
  navBar: {
    account: 'My Account',
    signIn: 'Log in',
    signUp: 'Sign Up',
    logout: 'Logout',
    greeting: 'Hello',
    manageAccount: 'Manage Account',
    errors: {
      'auth/server-error': 'Server error',
    },
  },
  strengthBar: {
    level1: 'weak',
    level2: 'okay',
    level3: 'good',
    level4: 'strong',
    tooShort: 'too short',
  },
  login: {
    form: {
      title: 'Login',
      altTitle: 'Login via Link',
      reset: 'Reset',
      login: 'Login',
      or: 'or',
      forgotPassword: 'Forgot your password? Reset it here',
      notRegistered: 'Not registered? Click here to sign up',
    },
    email: {
      label: 'email',
      valid: 'please insert a valid email',
      required: 'email field is required',
    },
    password: {
      label: 'password',
      required: 'password field is required',
    },
    emailLink: {
      label: 'Email link login',
      tooltip: 'Sign in through a link sent to your email',
    },
    remember: {
      label: 'Remember me',
      tooltip: 'fewer logins',
      noStorage: 'cookies must be enabled to use this option',
    },
    sentMail: 'Email sent successfully to',
    sentLink: 'Sent Link',
    tryAgain: 'try again on',
    errors: {
      'auth/web-storage-unsupported': 'Cookies must be enabled to log in',
      'auth/user-not-found': 'This user has not been found',
      'auth/wrong-password': 'Wrong username or password',
      'auth/server-error': 'Server error',
      'auth/too-many-requests': 'Too many failed login attempts',
      'auth/quota-exceeded': 'Several link requests have been made from this address, please use another login method or login later',
      'auth/network-request-failed': 'There seems to be no Internet connection',
      'auth/multi-factor-auth-required': 'To continue it is necessary to authenticate with another method',
      'auth/invalid-credential': 'Incorrect email or password',
    },
    userNotFoundDialog: {
      title: 'User not Found',
      description: 'It seems that the account you are trying to access does not exist. Do you want to sign up?',
      positiveLabel: 'Yes',
      negativeLabel: 'No',
    },
  },
  mfaLogin: {
    title: 'Two-Factor Authentication',
    phone: {
      description: {
        prefix: 'Send an SMS code to the',
        suffix: 'phone to authenticate',
      },
      notSolvedCaptcha: 'Click "I\'m not a robot"',
      sendSMS: 'Send Code',
      wait: 'Code submitted, try again in',
      sendedSMS: 'The SMS code has been sent to your phone, if it doesn\'t arrive try again in a minute',
      errors: {
        'auth/invalid-verification-id': 'Invalid verification id',
        'auth/invalid-verification-code': 'The code entered has expired or is incorrect',
        'auth/undefined-verifier': 'Are you a robot?',
        'auth/network-request-failed': 'There seems to be no Internet connection.',
        'auth/server-error': 'Server error',
      },
    },
    totp: {
      enterCode: 'To continue, enter the code for one of the following apps where you enrolled this account',
      errors: {
        'auth/invalid-verification-code': 'The code entered has expired or is incorrect',
        'auth/network-request-failed': 'There seems to be no Internet connection.',
        'auth/server-error': 'Server error',
      },
    },
  },
  passwordReset: {
    form: {
      title: 'Reset Password',
      clean: 'Clean',
      reset: 'Reset Password',
      backToLogin: 'Return to the login window?',
      socialNetworks: 'Login with social networks?',
      clickHere: 'click here',
      notRegistered: 'Not registered? Click here to sign up',
    },
    email: {
      label: 'email',
      valid: 'please insert a valid email',
      required: 'email field is required',
    },
    sentMailDialog: {
      description: 'If there is a user with that email, a link to reset the password has been sent to',
      okLabel: 'Continue',
      cancelLabel: 'Retry',
    },
    errors: {
      'auth/user-not-found': 'User not Found',
      'auth/network-request-failed': 'There seems to be no Internet connection.',
      'auth/server-error': 'Server error',
    },
    userNotFoundDialog: {
      title: 'User not Found',
      description: 'It appears that the account you are trying to recover does not exist. Do you want to sign up?',
      positiveLabel: 'Yes',
      negativeLabel: 'No',
    },
  },
  signUp: {
    form: {
      title: 'Sign Up',
      reset: 'Reset',
      signUp: 'Sign Up',
      alreadyRegistered: 'Already registered?',
      socialNetworks: 'Login with social networks?',
      clickHere: 'click here',
      unsolvedCaptcha: 'Click on "I\'m not a robot"',
    },
    email: {
      label: 'email',
      valid: 'please insert a valid email',
      required: 'email field is required',
    },
    confirmEmail: {
      label: 'confirm email',
      valid: 'please insert a valid email',
      required: 'email must be confirmed',
      matchError: 'emails must match',
      matchSuccess: 'emails match',
    },
    password: {
      label: 'password',
      max: 'password must be at most 64 characters',
      min: 'password must be at least 8 characters',
      required: 'password field is required',
    },
    remember: {
      label: 'Remember me',
      tooltip: 'fewer logins',
      noStorage: 'cookies must be enabled to use this option',
    },
    errors: {
      'auth/web-storage-unsupported': 'This account has probably been created. Cookies must be enabled if you want to log in',
      'auth/email-already-in-use': 'This email is already in use',
      'auth/network-request-failed': 'There seems to be no Internet connection.',
      'auth/server-error': 'Server error',
    },
    existentAccountDialog: {
      title: 'Existent Account',
      description: 'It seems that the account you are trying to create already exists. Do you want to log in instead?',
      positiveLabel: 'Yes',
      negativeLabel: 'No',
    },
    cookiesErrorDialog: {
      title: 'Cookies are blocked',
      description: 'This account has probably been created. Cookies must be enabled if you want to log in',
      positiveLabel: 'Continue',
    },
  },
  emailSign: {
    email: {
      label: 'email',
      valid: 'please insert a valid email',
      required: 'email field is required',
    },
    errors: {
      'auth/web-storage-unsupported': 'Cookies must be enabled to log in',
      'auth/invalid-action-code': 'This link is expired or has already been used',
      'auth/expired-action-code': 'This link is expired',
      'auth/invalid-email': "This email don't match the one the link was sent to",
      'auth/multi-factor-auth-required': 'Para continuar es necesario autenticarse con otro método',
      'auth/network-request-failed': 'There seems to be no Internet connection.',
      'auth/server-error': 'Server error',
    },
    setPassword: {
      title: 'Set Password',
      firstDescription: 'When logging in for the first time through an email link, the established password is disabled. If you wish, you can set it by entering it again or choosing a new password in the form below.',
      secondDescription: 'You can skip this step and then set the password in the login window by clicking on "Forgot Password", or in the "Manage Account" window when logging into the app using a new email link.',
    },
    verificatedPrefix: 'Successfully verified the ',
    verificatedSuffix: ' email',
    mfaVerificated: 'Verified email, you can now continue to set up two-factor authentication',
    enrollReauthenticated: 'Re-authenticated user, can now continue to set up two-factor authentication',
    unenrollReauthenticated: 'Re-authenticated user, can now continue to disable two-factor authentication',
    setpasswordReauthenticated: 'Reauthenticated user, can now continue to set or change the password',
    deleteReauthenticated: 'Reauthenticated user, can now continue deleting your account',
  },
  manageAccount: {
    title: 'Manage Account',
    accountVerification: 'Account Verification',
    setPassword: 'Set or change the password',
    changePassword: 'Change Password',
    preferences: 'Preferences',
    cookiesStorage: 'Cookies Storage',
    twoFactorAuthentication: 'Two-Factor Authentication',
    deleteAccount: 'Delete Account',
  },
  accountVerification: {
    verifiedEmail: 'Verified Email',
    notVerifiedEmailTitle: 'Email not verified',
    notVerifiedEmailDefaultMessage: 'To verify this email you must enter through a link.',
    notVerifiedEmailMFAMessage: 'To activate two-factor authentication, you must first verify the email by entering through a link',
    sendLink: 'Send verification link',
    sentMail: 'The email with the verification link has been successfully sent to',
    remember: {
      label: 'Remember me',
      tooltip: 'fewer logins',
      noStorage: 'cookies must be enabled to use this option',
    },
    errors: {
      'auth/server-error': 'Server error',
      'auth/quota-exceeded': 'Several link requests have been made from this address, please use another login method or login later',
      'auth/network-request-failed': 'There seems to be no Internet connection.',
    },
  },
  twoFactorAuthentication: {
    enrollReauthenticated: 'Re-authenticated user, can now continue to set up two-factor authentication',
  },
  mfaSwitch: {
    viaPhone: 'via phone',
    viaTOTP: 'via totp app',
  },
  mfaPhoneInputCode: {
    label: 'SMS Code',
    codeConfirm: 'Confirm SMS Code',
    onlyNumbers: 'You must enter only numbers',
    numChar: 'The code must have 6 numbers',
  },
  mfaTOTPInputCode: {
    label: 'Totp code',
    codeConfirm: 'Confirm totp Code',
    onlyNumbers: 'You must enter only numbers',
    numChar: 'The code must have 6 numbers',
  },
  mfaPhoneEnroll: {
    description: 'To activate two-step authentication, you need to enter a code that will be sent to your cell phone',
    enrolled: 'Phone successfully enrolled to enter as a second authentication factor',
    phone: {
      label: 'Phone',
      notValid: 'Enter a valid phone number',
      notSolvedCaptcha: 'Click "I\'m not a robot"',
      sendSMS: 'Send Code',
      wait: 'Code submitted, try again in',
      sendedSMS: 'The SMS code has been sent to your phone, if it doesn\'t arrive try again in a minute',
    },
    errors: {
      'auth/invalid-verification-id': 'Invalid verification id',
      'auth/invalid-verification-code': 'The code entered has expired or is incorrect',
      'auth/undefined-verifier': 'Are you a robot?',
      'auth/user-not-found': 'User not found',
      'auth/unverified-email': 'The email has not been verified',
      'auth/requires-recent-login': 'To enable two-factor authentication, you must have recently logged in to the app',
      'auth/user-token-expired': 'To enable two-factor authentication, you must have recently logged in to the app',
      'auth/network-request-failed': 'There seems to be no Internet connection.',
      'auth/server-error': 'Server error',
    },
  },
  mfaUnenroll: {
    phoneDescription: 'Two-step authentication is already enabled with the phone number',
    totpDescription: 'Two-factor authentication is already enabled with a code generated by one of the following apps',
    disablePhoneMFA: 'Disable two-factor authentication via phone',
    disableTotpMFA: 'Disable two-factor authentication via totp app',
    unenrolledPhoneMFA: 'Phone two-factor authentication has been successfully unenrolled',
    unenrolledTotpMFA: 'Totp app two-factor authentication has been successfully unenrolled',
    errors: {
      'auth/user-not-found': 'User not found',
      'auth/requires-recent-login': 'To disable two-factor authentication, you must have recently logged in to the app',
      'auth/user-token-expired': 'To disable two-factor authentication, you must have recently logged in to the app',
      'auth/network-request-failed': 'There seems to be no Internet connection.',
      'auth/server-error': 'Server error',
    },
  },
  mfaTotpEnroll: {
    generateQR: 'Generate QR Code',
    secretKey: 'Secret Key',
    clipboard: 'Copy to clipboard',
    secretKeyCopied: 'The secret key has been copied to the clipboard',
    downloadApp: '1. Download one of the following authenticator apps:',
    scanCode: '2. Scan the QR code or enter the secret key in the downloaded authenticator app.',
    enterCode: '3. Enter the code generated by the app:',
    enrolled: 'Token successfully enrolled to enter as a second authentication factor',
    showSecretKey: 'Show secret key',
    hideSecretKey: 'Hide secret key',
    errors: {
      'auth/invalid-verification-code': 'The code entered has expired or is incorrect',
      'auth/user-not-found': 'User not found',
      'auth/network-request-failed': 'There seems to be no Internet connection.',
      'auth/server-error': 'Server error',
    },
  },
  totpApps: {
    authy: 'Authy',
    ma: 'Microsoft Authenticator',
    ga: 'Google Authenticator',
  },
  reauthentication: {
    title: 'Confirm Identity',
    description: 'To perform this operation, you need to confirm your identity using any of the following access methods',
    form: {
      reset: 'Reset',
      confirm: 'Confirm',
      sendLink: 'Send Link',
      or: 'or',
      // facebookAlt: 'Continue with Facebook',
      // twitterAlt: 'Continue with Twitter',
      // forgotPassword: 'Forgot your password? Reset it here',
      // notRegistered: 'Not registered? Click here to sign up',
    },
    email: {
      label: 'email',
    },
    password: {
      label: 'password',
      required: 'password field is required',
    },
    emailLink: {
      label: 'Email link login',
      tooltip: 'Sign in through a link sent to your email',
    },
    sentMail: 'Email sent successfully to',
    sentLink: 'Sent Link',
    tryAgain: 'try again on',
    errors: {
      'auth/wrong-password': 'Wrong password',
      'auth/web-storage-unsupported': 'Cookies must be enabled to log in',
      'auth/server-error': 'Server error',
      'auth/quota-exceeded': 'Several link requests have been made from this address, please use another login method or login later',
      'auth/network-request-failed': 'There seems to be no Internet connection',
      'auth/multi-factor-auth-required': 'Para continuar es necesario autenticarse con otro método',
      'auth/invalid-credential': 'Wrong password',
    },
  },
  socialProviders: {
    providerSignInErrors: {
      'auth/multi-factor-auth-required': 'To continue it is necessary to authenticate with another method',
      'auth/account-exists-with-different-credential': 'This email is already used to log in in one or other ways. To log in with this provider, first log in another way and then link this provider from the user options',
      'auth/web-storage-unsupported': 'It seems that cookies are disabled for this page',
      'auth/popup-blocked': 'Pop-ups are blocked for this page',
      'auth/cancelled-popup-request': 'There was already a login window open with the provider, only the last one will give access',
      'auth/popup-closed-by-user': 'The window to log in with the provider has been closed',
      'auth/server-error': 'Server error',
      'auth/user-not-signed': 'User is not logged in',
      'auth/internal-error': 'There seems to be no internet connection',
    },
    existingSignInMethods: {
      prefix: 'This email is already used to enter through',
      and: 'and',
      suffix: 'To log in this way, first log in with one of the mentioned providers and then link this provider from the user options.',
      password: 'email and password',
      emailLink: 'link via email',
    },
    facebookAlt: 'Continue with Facebook',
    twitterAlt: 'Continue with Twitter',
  },
  setPassword: {
    form: {
      reset: 'Reset',
      setPassword: 'Set Password',
      successSet: 'Password set successfully',
    },
    password: {
      label: 'password',
      max: 'password must be at most 64 characters',
      min: 'password must be at least 8 characters',
      required: 'password field is required',
    },
    confirmPassword: {
      label: 'confirm password',
      required: 'password must be confirmed',
      matchError: 'passwords must match',
      matchSuccess: 'passwords match',
    },
    errors: {
      'auth/user-not-found': 'User not found',
      'auth/requires-recent-login': 'To set a password, you must have recently logged in to the app',
      'auth/user-token-expired': 'To set a password, you must have recently logged in to the app',
      'auth/server-error': 'Server error',
      'auth/network-request-failed': 'There seems to be no Internet connection',
    },
  },
  preferences: {
    displayName: {
      label: 'Display Name',
      required: 'The "display name" field should not be empty',
      profane: 'Username Not Allowed',
      max: 'Display name is too long',
    },
    avatar: {
      profilePicture: 'Profile picture',
      uploadPicture: 'Upload picture',
      clearPicture: 'Clear picture',
      notTouched: 'Picture has not been edited',
    },
    reset: 'Reset',
    updatePreferences: 'Update preferences',
    sameValuesTooltip: 'To update you must modify one of the fields',
    errors: {
      'auth/user-not-found': 'User not found',
      'storage/server-error': 'Storage Service Failed',
      'auth/server-error': 'Server error',
      'storage/unauthorized': 'Storage service not available',
      'storage/retry-limit-exceeded': 'There seems to be no Internet connection',
      'auth/network-request-failed': 'There seems to be no Internet connection',
      'profanity-filter/nsfw-image': 'User photo may contain inappropriate content',
      'profanity-filter/nsfw-name': 'Username may contain inappropriate content',
    },
    preferencesUpdated: 'Preferences have been successfully updated',
  },
  cookiesStorage: {
    enable: 'enable',
    disable: 'disable',
    description: 'If you enable cookies, you can improve the user experience, automatically saving preferences such as: language, keep the session logged in, among others.',
    eraseCookies: 'Erase cookies',
    showCookies: 'Show Cookies',
    hideCookies: 'Hide Cookies',
    reset: 'Reset',
    update: 'Update',
    noChangesTooltip: 'No changes have been made',
    noCookiesStoraged: 'No cookies storaged',
    cookiesEnabled: 'Cookies have been enabled',
    cookiesDisabled: 'Cookies have been disabled',
  },
  eraseAccount: {
    warning: 'Here you can permanently delete your account. All data associated with this account will be deleted as well and it will be impossible to recover it in the future.',
    deleteData: 'I understand that by deleting my account all data associated with it will be permanently deleted',
    deleteAccount: 'I want to delete my account',
    delete: 'Delete account',
    notSelected: 'To continue, select both checkboxes',
    deleteReauthenticated: 'Reauthenticated user, can now continue deleting your account',
    errors: {
      'storage/unauthorized': 'Storage service not available',
      'storage/server-error': 'Storage Service Failed',
      'auth/user-not-found': 'User not found',
      'auth/requires-recent-login': 'To delete your account, you must have recently logged in to the app',
      'auth/user-token-expired': 'To delete your account, you must have recently logged in to the app',
      'auth/network-request-failed': 'There seems to be no Internet connection.',
      'auth/server-error': 'Server error',
    },
  },
  withAuth: {
    signing: 'trying to signing you in',
    noInternetConnection: {
      title: 'No internet connection',
      description: 'There seems to be no internet connection. Check the connection first, and then refresh the page.',
      primaryActionLabel: 'Try Again',
      secondaryActionLabel: 'Return to Home Page',
    },
  },
  cookieConsent: {
    title: 'Consent to the storage of Cookies',
    storage: {
      message: 'This application uses cookies to improve the user experience, automatically saving preferences such as: language, keep the session signed, among others',
      agree: 'I agree',
      disagree: 'I disagree',
    },
    notStorage: {
      message: 'Cookies are disabled in this browser, so it will not be possible to improve the user experience, automatically saving preferences such as: language, keep the session login, among others',
      understand: 'I understand',
    },
  },
  pageNotFound: {
    title: 'Page Not Found',
    description: 'The page you are looking for has not been found',
    primaryActionLabel: 'Return to Home Page',
  },
};

export default english;
